# Generated by Django 5.0.10 on 2025-01-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('text', models.TextField(verbose_name='Текст статьи')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
