# Generated by Django 5.0.10 on 2025-01-13 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='type')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='TypeTechnic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='type')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Тип техники',
                'verbose_name_plural': 'Типы техники',
            },
        ),
        migrations.CreateModel(
            name='Technic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='technic/', verbose_name='Изображение')),
                ('number', models.CharField(blank=True, max_length=8, null=True, verbose_name='Гос. номер')),
                ('invnumber', models.IntegerField(blank=True, null=True, verbose_name='Инвентарный номер')),
                ('imei', models.IntegerField(blank=True, null=True, verbose_name='IMEI')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic.department', verbose_name='Подразделение')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic.typetechnic', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Техника',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=100, verbose_name='Работа')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание работ')),
                ('technic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic.technic')),
            ],
            options={
                'verbose_name': 'Тех. обслуживание',
                'verbose_name_plural': 'Тех. обслуживания',
            },
        ),
    ]
