# Generated by Django 5.0.10 on 2025-01-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='imei',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='IMEI'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='invnumber',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='typetechnic',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='typetechnic',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип'),
        ),
    ]
